import colorsys
P = {
 "base":"#141518","low":"#1B1C21","surface":"#18191D","overlay":"#1F2026","med":"#2A2C34","high":"#383A43",
 "text":"#9DA4B2","iron":"#8F97A6","subtle":"#7F8797","muted":"#5E6577","faint":"#454A58",
 "rose":"#B98590","gold":"#BFA077","foam":"#7AA3B5","teal":"#7BA09F","iris":"#9A8EB9","love":"#BA6B70",
 "search_bg":"#2C3745","err_bg":"#271C1F","git_add_bg":"#182421","git_change_bg":"#1B1F28","git_del_bg":"#261B1E",
}
def rgb(h): return tuple(int(h[i:i+2],16)/255 for i in (1,3,5))
def hsl(h):
    r,g,b=rgb(h); hh,l,s=colorsys.rgb_to_hls(r,g,b); return round(hh*360),round(s*100),round(l*100)
def blend(a,b,t):
    ra,rb=rgb(a),rgb(b); return "#%02X%02X%02X"%tuple(round(255*(x*(1-t)+y*t)) for x,y in zip(ra,rb))
def hsl_str(h): H,S,L=hsl(h); return f"{H}deg {S}% {L}%"
STEPS=[50,100,200,300,400,500,600,700,800,900,950]
def ramp(anchor):
    H,S,L=hsl(anchor)
    hi=[92,88,80,72,64]; lo=[46,39,32,27,16]
    out=[]
    # interpolate: 400 sits between anchor and 64 etc; keep anchor at 500
    for i,st in enumerate(STEPS):
        if st<500:
            # 50..400 : from 92 down toward L; scale hi so 400 ~ L+8
            top=92; frac=[0,0.11,0.33,0.55,0.78][i]
            l=round(top-(top-(L+8))*frac) if L+8<top else L
        elif st==500: l=L
        else:
            frac=[0.25,0.45,0.62,0.75,1.0][i-6]
            l=round(L-(L-14)*frac)
        out.append((st,H,S,l))
    return out
fam={
 "red":("love",P["love"]),
 "rose":("rose",P["rose"]),
 "pink":("blend(rose, iris)",blend(P["rose"],P["iris"],0.4)),
 "orange":("blend(gold, love)",blend(P["gold"],P["love"],0.45)),
 "amber":("blend(gold, love 0.2)",blend(P["gold"],P["love"],0.2)),
 "yellow":("gold",P["gold"]),
 "lime":("blend(gold, teal)",blend(P["gold"],P["teal"],0.5)),
 "green":("teal",P["teal"]),
 "emerald":("teal",P["teal"]),
 "teal":("teal",P["teal"]),
 "cyan":("foam",P["foam"]),
 "sky":("foam",P["foam"]),
 "blue":("foam",P["foam"]),
 "indigo":("blend(foam, iris)",blend(P["foam"],P["iris"],0.5)),
 "violet":("iris",P["iris"]),
 "purple":("iris",P["iris"]),
}
lines=[]
lines.append("@layer theme {")
lines.append("  /*")
lines.append("   * Yūgure (夕暮れ) — design-token ramps generated from the yugure palette.")
lines.append("   *")
lines.append("   * Hexes mirror nvim/lua/yugure/palette.lua. Generated by")
lines.append("   * inkdrop/yugure/scripts/gen-tokens.py; edit the palette there, not here.")
lines.append("   *")
lines.append("   * Yugure has six accent hues and a neutral ladder; Inkdrop wants 17")
lines.append("   * Tailwind-style families. Each family anchors a yugure accent at step")
lines.append("   * 500 (hue/saturation held, lightness interpolated). Families yugure")
lines.append("   * has no hue for (green, blue, sky, …) reuse the nearest accent rather")
lines.append("   * than inventing a colour: a new colour is a new role, not a new shade.")
lines.append("   */")
lines.append("  :root {")
lines.append("    /* Raw yugure palette as hsl triplets — use as hsl(var(--yugure-x) / a%) */")
for k,v in P.items():
    lines.append(f"    --yugure-{k.replace('_','-')}: {hsl_str(v)}; /* {v} */")
lines.append("")
lines.append("    /* Neutral — text → iron → subtle → muted → faint → high → med → overlay → base */")
neut=[(50,blend(P["text"],"#FFFFFF",0.35)),(100,blend(P["text"],"#FFFFFF",0.18)),(200,P["text"]),(300,P["iron"]),(400,P["subtle"]),(500,P["muted"]),(600,P["faint"]),(700,P["high"]),(800,P["med"]),(900,P["overlay"]),(950,P["base"])]
for st,h in neut:
    lines.append(f"    --hsl-neutral-{st}: {hsl_str(h)}; /* {h} */")
lines.append("")
for name,(src,anchor) in fam.items():
    lines.append(f"    /* {name.capitalize()} — {src} ({anchor}) */")
    for st,H,S,L in ramp(anchor):
        lines.append(f"    --hsl-{name}-{st}: {H}deg {S}% {L}%;")
    lines.append("")
lines.append("    /* --color-* aliases so components reading the resolved colour see yugure too */")
for name in ["neutral"]+list(fam.keys()):
    for st in STEPS:
        lines.append(f"    --color-{name}-{st}: hsl(var(--hsl-{name}-{st}));")
lines.append("  }")
lines.append("}")
open("/Users/stoykotolev/.config/inkdrop/yugure/styles/tokens.css","w").write("\n".join(lines)+"\n")
print("ok")
for k,v in P.items(): print(k, v, hsl_str(v))
for name,(src,anchor) in fam.items(): print(name, anchor, [l for _,_,_,l in ramp(anchor)])
